<?php /* @var $this Helti100_Varnish_Block_Beforebodyend */?>
<script type="text/javascript">
//<![CDATA[
    var AJAXHOME_URL = '<?php echo Mage::getUrl('varnish/blocks/get', Mage::app()->getStore()->isCurrentlySecure() ? array('_secure' => 1) : array()) ?>'; 
    var FULLACTIONNAME = '<?php echo $this->getAction()->getFullActionName() ?>';
    <?php if (($_product = Mage::registry('product')) == true) : ?>
    var CURRENTPRODUCTID = '<?php echo $_product->getId() ?>';
    <?php endif; ?>
//]]>
</script>
